repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.77.0 # always use latest
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_tflint
      - id: terraform_docs
      - id: terraform_checkov
